name: flame_shells
description: Beautiful and easy to use widgets that emulates console shells for your Flame game
version: 0.0.1
homepage: https://github.com/flame-engine/flame_shells

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flame: 1.0.0-rc3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
